# https://taskfile.dev

version: '3'

# Global variables available to all tasks
vars:
  DOPPLER_PROJECT: "project-dockerlab"
  DOPPLER_CONFIG: "dev"

includes:
  ansible: ./taskfile/ansible.yml
  tf: ./taskfile/terraform.yml
  tfa: ./taskfile/terraform_apps.yml

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
