---
# Dokploy installation playbook
- name: "Install and configure Dokploy"
  hosts: swarm_managers
  become: true
  tags: ["dokploy"]
  vars:
    # Dokploy configuration variables - using environment lookups for security
    dokploy_port: "{{ lookup('env', 'DOKPLOY_PORT') | default('3000', true) }}"
    traefik_ssl_port: "{{ lookup('env', 'TRAEFIK_SSL_PORT') | default('443', true) }}"
    traefik_port: "{{ lookup('env', 'TRAEFIK_PORT') | default('80', true) }}"
    dokploy_release_tag: "{{ lookup('env', 'DOKPLOY_RELEASE_TAG') | default('latest', true) }}"
    dokploy_database_url: "{{ lookup('env', 'DOKPLOY_DATABASE_URL') | default('postgresql://dokploy:amukds4wi9001583845717ad2@dokploy-postgres:5432/dokploy', true) }}"
    dokploy_redis_host: "{{ lookup('env', 'DOKPLOY_REDIS_HOST') | default('dokploy-redis', true) }}"
    dokploy_tz: "{{ lookup('env', 'DOKPLOY_TZ') | default('UTC', true) }}"
    dokploy_postgres_password: "{{ lookup('env', 'DOKPLOY_POSTGRES_PASSWORD') | default('amukds4wi9001583845717ad2', true) }}"
    dokploy_postgres_user: "{{ lookup('env', 'DOKPLOY_POSTGRES_USER') | default('dokploy', true) }}"
    dokploy_postgres_db: "{{ lookup('env', 'DOKPLOY_POSTGRES_DB') | default('dokploy', true) }}"
    dokploy_redis_password: "{{ lookup('env', 'DOKPLOY_REDIS_PASSWORD') | default('', true) }}"

  pre_tasks:
    - name: "Check if Dokploy service exists"
      ansible.builtin.command: docker service inspect dokploy
      register: dokploy_exists
      failed_when: false
      changed_when: false
      check_mode: false

    - name: "Check if Traefik container exists"
      ansible.builtin.command: docker inspect dokploy-traefik
      register: traefik_exists
      failed_when: false
      changed_when: false
      check_mode: false

    - name: "Verify required ports are available"
      ansible.builtin.command: ss -tulnp
      register: port_check
      changed_when: false
      check_mode: false
      when:
        - dokploy_exists.rc != 0
        - traefik_exists.rc != 0

    - name: "Check if ports are in use"
      ansible.builtin.fail:
        msg: "Port {{ item }} is already in use. Dokploy requires ports 80, 443, and 3000 to be available."
      when:
        - dokploy_exists.rc != 0
        - traefik_exists.rc != 0
        - port_check.stdout is search(':' ~ item ~ ' ')
      loop: [80, 443, 3000]

    - name: "Ensure Docker Swarm is initialized"
      ansible.builtin.command: "docker swarm init --advertise-addr {{ ansible_facts['tailscale0']['ipv4']['address'] }}"
      when:
        - ansible_facts['tailscale0'] is defined
        - ansible_facts['tailscale0']['ipv4'] is defined
        - ansible_facts['tailscale0']['ipv4']['address'] is defined
      register: swarm_init
      failed_when:
        - swarm_init.rc != 0
        - "'already part of a swarm' not in swarm_init.stderr"
      changed_when: "'Swarm initialized' in swarm_init.stdout"

    - name: "Get advertise address"
      ansible.builtin.set_fact:
        dokploy_advertise_addr: "{{ ansible_facts['tailscale0']['ipv4']['address'] }}"
      when:
        - ansible_facts['tailscale0'] is defined
        - ansible_facts['tailscale0']['ipv4'] is defined
        - ansible_facts['tailscale0']['ipv4']['address'] is defined

  tasks:
    - name: "Check if Dokploy network exists"
      ansible.builtin.command: docker network inspect dokploy-network
      register: network_check
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: "Create Dokploy network"
      ansible.builtin.command: docker network create --driver overlay --attachable dokploy-network
      when: network_check.rc != 0
      register: network_create
      changed_when: "'Created' in network_create.stdout"

    - name: "Create Dokploy configuration directory"
      ansible.builtin.file:
        path: /etc/dokploy
        state: directory
        mode: '0777'

    - name: "Create Traefik configuration directory"
      ansible.builtin.file:
        path: /etc/dokploy/traefik
        state: directory
        mode: '0755'

    - name: "Create Traefik dynamic configuration directory"
      ansible.builtin.file:
        path: /etc/dokploy/traefik/dynamic
        state: directory
        mode: '0755'

    - name: "Create Traefik configuration file"
      ansible.builtin.template:
        src: traefik.yml
        dest: /etc/dokploy/traefik/traefik.yml
        mode: '0644'

    - name: "Pull required Docker images"
      ansible.builtin.shell: |
        if ! docker image inspect {{ item }} >/dev/null 2>&1; then
          docker pull {{ item }}
        fi
      loop:
        - "traefik:v3.6.1"
        - "dokploy/dokploy:{{ dokploy_release_tag }}"
        - "postgres:16"
        - "redis:7"
      register: image_pull
      changed_when: image_pull.stdout | length > 0

    - name: "Create PostgreSQL service"
      ansible.builtin.shell: |
        if ! docker service inspect dokploy-postgres >/dev/null 2>&1; then
          docker service create \
            --name dokploy-postgres \
            --constraint 'node.hostname==dkr-srv-0' \
            --network dokploy-network \
            --env POSTGRES_USER={{ dokploy_postgres_user }} \
            --env POSTGRES_DB={{ dokploy_postgres_db }} \
            --env POSTGRES_PASSWORD={{ dokploy_postgres_password }} \
            --mount type=volume,source=dokploy-postgres,target=/var/lib/postgresql/data \
            postgres:16
        fi
      register: postgres_service
      changed_when: postgres_service.stdout | length > 0

    - name: "Create Redis service"
      ansible.builtin.shell: |
        if ! docker service inspect dokploy-redis >/dev/null 2>&1; then
          docker service create \
            --name dokploy-redis \
            --constraint 'node.hostname==dkr-srv-0' \
            --network dokploy-network \
            --mount type=volume,source=dokploy-redis,target=/data \
            redis:7
        fi
      register: redis_service
      changed_when: redis_service.stdout | length > 0

    - name: "Create Dokploy service"
      ansible.builtin.shell: |
        if ! docker service inspect dokploy >/dev/null 2>&1; then
          docker service create \
            --name dokploy \
            --replicas 1 \
            --network dokploy-network \
            --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
            --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
            --mount type=volume,source=dokploy,target=/root/.docker \
            --publish published={{ dokploy_port }},target={{ dokploy_port }},mode=host \
            --update-parallelism 1 \
            --update-order stop-first \
            --constraint 'node.hostname == dkr-srv-0' \
            -e ADVERTISE_ADDR={{ dokploy_advertise_addr }} \
            -e DATABASE_URL={{ dokploy_database_url }} \
            -e REDIS_HOST={{ dokploy_redis_host }} \
            -e TZ={{ dokploy_tz }} \
            dokploy/dokploy:{{ dokploy_release_tag }}
        fi
      register: dokploy_service
      changed_when: dokploy_service.stdout | length > 0

    - name: "Create Traefik service"
      ansible.builtin.shell: |
        if ! docker inspect dokploy-traefik >/dev/null 2>&1; then
          docker run -d \
            --name dokploy-traefik \
            --restart always \
            -v /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml \
            -v /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -p {{ traefik_port }}:80/tcp \
            -p {{ traefik_ssl_port }}:443/tcp \
            -p {{ traefik_ssl_port }}:443/udp \
            traefik:v3.6.1
        fi
      register: traefik_service
      changed_when: traefik_service.stdout | length > 0

    - name: "Connect Traefik to Dokploy network"
      ansible.builtin.shell: |
        if ! docker network inspect dokploy-network | grep -q dokploy-traefik; then
          docker network connect dokploy-network dokploy-traefik
        fi
      register: traefik_connect
      changed_when: traefik_connect.stdout | length > 0


  post_tasks:
    - name: "Wait for services to be ready"
      ansible.builtin.command: sleep 15
      changed_when: false

    - name: "Check Dokploy service status"
      ansible.builtin.command: docker service ps dokploy
      register: dokploy_status
      changed_when: false

    - name: "Check Traefik container status"
      ansible.builtin.command: docker ps --filter "name=dokploy-traefik"
      register: traefik_status
      changed_when: false

    - name: "Identify Swarm Leader"
      ansible.builtin.shell: |
        docker node ls --filter "role=manager" --format "{% raw %}{{.Hostname}} {{.ManagerStatus}}{% endraw %}" | grep "Leader" | awk '{print $1}'
      register: swarm_leader_hostname
      changed_when: false
      check_mode: false

    - name: "Identify Leader Tailscale IP"
      ansible.builtin.set_fact:
        dokploy_leader_ip: "{{ hostvars[swarm_leader_hostname.stdout].ansible_facts['tailscale0']['ipv4']['address'] }}"
      when: swarm_leader_hostname.stdout in hostvars

    - name: "Display installation summary"
      ansible.builtin.debug:
        msg: |
          Dokploy installation completed successfully!

          Services Status:
          - Dokploy: {{ dokploy_status.stdout_lines | join('\n') }}
          - Traefik: {{ traefik_status.stdout_lines | join('\n') }}

          Main Access Point (Swarm Leader):
          Access Dokploy at: http://{{ dokploy_leader_ip | default(dokploy_advertise_addr) }}:{{ dokploy_port }}

          Configuration:
          - Leader Hostname: {{ swarm_leader_hostname.stdout }}
          - Advertise Address: {{ dokploy_advertise_addr }}
          - Dokploy Port: {{ dokploy_port }}
          - Traefik HTTP Port: {{ traefik_port }}
          - Traefik HTTPS Port: {{ traefik_ssl_port }}
          - Database: PostgreSQL (dokploy-postgres)
          - Cache: Redis (dokploy-redis)
          - Release Tag: {{ dokploy_release_tag }}
          - Timezone: {{ dokploy_tz }}
