---
# Komodo installation and configuration playbook
# Based on: https://komo.do/docs/setup/mongo

# Environment Variables Required (to be added to Doppler):
# ------------------------------------------------------
# KOMODO_HOST                 - The external URL/IP for Komodo (e.g. http://100.x.x.x:9120)
# KOMODO_TITLE                - Title for the Komodo instance
# KOMODO_PASSKEY              - [MANDATORY] Important! Used for Core/Periphery auth
# KOMODO_JWT_SECRET           - [MANDATORY] For JWT tokens
# KOMODO_WEBHOOK_SECRET       - [MANDATORY] For webhooks
# KOMODO_DB_USERNAME          - MongoDB root username
# KOMODO_DB_PASSWORD          - [MANDATORY] MongoDB root password
# KOMODO_INIT_ADMIN_USERNAME  - Initial admin username
# KOMODO_INIT_ADMIN_PASSWORD  - [MANDATORY] Initial admin password
# COMPOSE_KOMODO_IMAGE_TAG    - Image tag (default: latest)
# COMPOSE_KOMODO_BACKUPS_PATH - Path for backups (default: /opt/data/komodo/backups)
# PERIPHERY_ROOT_DIRECTORY    - Path for periphery files (default: /etc/komodo)

# Komodo installation following official documentation
# Based on: https://komo.do/docs/setup/mongo
# Uses the official mongo.compose.yaml approach

- name: "Install and configure Komodo on cloud node"
  hosts: swarm_managers
  become: true
  tags: ["komodo", "applications"]
  vars:
    # Komodo configuration
    komodo_host: "{{ lookup('env', 'KOMODO_HOST') | default('http://localhost:9120', true) }}"
    komodo_title: "{{ lookup('env', 'KOMODO_TITLE') | default('Komodo', true) }}"
    komodo_passkey: "{{ lookup('env', 'KOMODO_PASSKEY') | default('change-this-passkey', true) }}"
    komodo_webhook_secret: "{{ lookup('env', 'KOMODO_WEBHOOK_SECRET') | default('change-this-webhook-secret', true) }}"
    komodo_jwt_secret: "{{ lookup('env', 'KOMODO_JWT_SECRET') | default('change-this-jwt-secret', true) }}"

    # Database credentials
    komodo_db_username: "{{ lookup('env', 'KOMODO_DB_USERNAME') | default('admin', true) }}"
    komodo_db_password: "{{ lookup('env', 'KOMODO_DB_PASSWORD') | default('admin', true) }}"

    # Initial admin user
    komodo_admin_username: "{{ lookup('env', 'KOMODO_INIT_ADMIN_USERNAME') | default('admin', true) }}"
    komodo_admin_password: "{{ lookup('env', 'KOMODO_INIT_ADMIN_PASSWORD') | default('changeme', true) }}"

    # Paths
    komodo_backups_path: "{{ lookup('env', 'COMPOSE_KOMODO_BACKUPS_PATH') | default('/opt/data/komodo/backups', true) }}"
    komodo_mongo_data_path: "/opt/data/komodo/mongo-data"
    komodo_mongo_config_path: "/opt/data/komodo/mongo-config"
    periphery_root: "{{ lookup('env', 'PERIPHERY_ROOT_DIRECTORY') | default('/etc/komodo', true) }}"

    # Image tag
    komodo_image_tag: "{{ lookup('env', 'COMPOSE_KOMODO_IMAGE_TAG') | default('latest', true) }}"

  tasks:
    - name: "Get node labels"
      ansible.builtin.shell: |
        docker node inspect {{ inventory_hostname }} --format '{{ "{{" }}.Spec.Labels{{ "}}" }}'
      register: node_labels
      changed_when: false
      check_mode: false
      ignore_errors: true

    - name: "Check if this node has role=cloud label"
      ansible.builtin.set_fact:
        has_cloud_role: "{{ 'role:cloud' in node_labels.stdout }}"
      when: node_labels.rc == 0

    - name: "Check if this is the swarm leader"
      ansible.builtin.shell: |
        docker node ls --filter "role=manager" --format "{% raw %}{{.Hostname}} {{.ManagerStatus}}{% endraw %}" | grep "Leader" | awk '{print $1}'
      register: swarm_leader_hostname
      changed_when: false
      check_mode: false

    - name: "Check if this is the cloud node and swarm leader"
      ansible.builtin.set_fact:
        is_cloud_leader: "{{ inventory_hostname == swarm_leader_hostname.stdout and has_cloud_role | default(false) }}"

    - name: "Debug - Show active tags"
      ansible.builtin.debug:
        var: ansible_run_tags
      run_once: true

    - name: "Stop Komodo stack for reset"
      ansible.builtin.shell: |
        docker stack rm komodo
        cd /opt/stacks/komodo && docker compose down --remove-orphans
      when: is_cloud_leader
      register: stack_rm_result
      failed_when: false
      changed_when: "'Removing' in stack_rm_result.stdout or 'Stopped' in stack_rm_result.stdout"
      tags: ["reset"]

    - name: "Wait for stack removal"
      ansible.builtin.pause:
        seconds: 15
      when: is_cloud_leader
      tags: ["reset"]

    - name: "Wipe Komodo data directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ komodo_mongo_data_path }}"
        - "{{ komodo_mongo_config_path }}"
      when: is_cloud_leader
      register: wipe_result
      tags: ["reset"]

    - name: "Verify data wipe"
      ansible.builtin.debug:
        msg: "Wiped directory {{ item.item }} - Changed: {{ item.changed }}"
      loop: "{{ wipe_result.results | default([]) }}"
      when: is_cloud_leader
      tags: ["reset"]

    - name: "Create Komodo Periphery directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ periphery_root }}"

    - name: "Create Komodo Core/Mongo directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/stacks/komodo
        - "{{ komodo_backups_path }}"
        - "{{ komodo_mongo_data_path }}"
        - "{{ komodo_mongo_config_path }}"
      when: is_cloud_leader

    - name: "Create Komodo compose.env file"
      ansible.builtin.copy:
        dest: /opt/stacks/komodo/compose.env
        mode: '0600'
        content: |
          ## Komodo Image Tag
          COMPOSE_KOMODO_IMAGE_TAG={{ komodo_image_tag }}

          ## Backups path
          COMPOSE_KOMODO_BACKUPS_PATH={{ komodo_backups_path }}

          ## Database credentials
          KOMODO_DB_USERNAME={{ komodo_db_username }}
          KOMODO_DB_PASSWORD={{ komodo_db_password }}

          ## Passkey for Core/Periphery authentication
          KOMODO_PASSKEY={{ komodo_passkey }}

          ## Timezone
          TZ={{ ansible_facts.date_time.tz }}

          #=-------------------------=#
          #= Komodo Core Environment =#
          #=-------------------------=#

          KOMODO_HOST={{ komodo_host }}
          KOMODO_TITLE={{ komodo_title }}
          KOMODO_FIRST_SERVER=https://periphery:8120
          KOMODO_FIRST_SERVER_NAME=Local
          KOMODO_DISABLE_CONFIRM_DIALOG=false

          KOMODO_MONITORING_INTERVAL="15-sec"
          KOMODO_RESOURCE_POLL_INTERVAL="1-hr"

          KOMODO_WEBHOOK_SECRET={{ komodo_webhook_secret }}
          KOMODO_JWT_SECRET={{ komodo_jwt_secret }}
          KOMODO_JWT_TTL="1-day"

          ## Local auth settings
          KOMODO_LOCAL_AUTH=true
          KOMODO_INIT_ADMIN_USERNAME={{ komodo_admin_username }}
          KOMODO_INIT_ADMIN_PASSWORD={{ komodo_admin_password }}
          KOMODO_DISABLE_USER_REGISTRATION=false
          KOMODO_ENABLE_NEW_USERS=true
          KOMODO_DISABLE_NON_ADMIN_CREATE=false
          KOMODO_TRANSPARENT_MODE=false

          KOMODO_LOGGING_PRETTY=false
          KOMODO_PRETTY_STARTUP_CONFIG=false

          #=------------------------------=#
          #= Komodo Periphery Environment =#
          #=------------------------------=#

          PERIPHERY_ROOT_DIRECTORY={{ periphery_root }}
          PERIPHERY_PASSKEYS=${KOMODO_PASSKEY}
          PERIPHERY_DISABLE_TERMINALS=false
          PERIPHERY_SSL_ENABLED=true
          PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
          PERIPHERY_LOGGING_PRETTY=false
          PERIPHERY_PRETTY_STARTUP_CONFIG=false
      when: is_cloud_leader

    - name: "Create Komodo network"
      ansible.builtin.docker_network:
        name: komodo_net
        driver: overlay
        state: present
        attachable: true
        scope: swarm
      when: is_cloud_leader

    - name: "Create Komodo docker-compose.yml (Docker Swarm compatible)"
      ansible.builtin.copy:
        dest: /opt/stacks/komodo/docker-compose.yml
        mode: '0644'
        content: |
          services:
            mongo:
              image: mongo:7
              command: --quiet --wiredTigerCacheSizeGB 0.25
              networks:
                - komodo_net
              volumes:
                - {{ komodo_mongo_data_path }}:/data/db
                - {{ komodo_mongo_config_path }}:/data/configdb
              environment:
                MONGO_INITDB_ROOT_USERNAME: "{{ komodo_db_username }}"
                MONGO_INITDB_ROOT_PASSWORD: "{{ komodo_db_password }}"
              deploy:
                placement:
                  constraints:
                    - node.role == manager
                    - node.labels.role == cloud
                restart_policy:
                  condition: any
                  delay: 5s

            core:
              image: "ghcr.io/moghtech/komodo-core:{{ komodo_image_tag }}"
              user: root
              depends_on:
                - mongo
              ports:
                - "9120:9120"
              networks:
                - komodo_net
              environment:
                KOMODO_DATABASE_ADDRESS: "mongo:27017"
                KOMODO_DATABASE_USERNAME: "{{ komodo_db_username }}"
                KOMODO_DATABASE_PASSWORD: "{{ komodo_db_password }}"
                KOMODO_HOST: "{{ komodo_host }}"
                KOMODO_TITLE: "{{ komodo_title }}"
                KOMODO_FIRST_SERVER: "https://periphery:8120"
                KOMODO_FIRST_SERVER_NAME: "Local"
                KOMODO_DISABLE_CONFIRM_DIALOG: "false"
                KOMODO_MONITORING_INTERVAL: "15-sec"
                KOMODO_RESOURCE_POLL_INTERVAL: "1-hr"
                KOMODO_WEBHOOK_SECRET: "{{ komodo_webhook_secret }}"
                KOMODO_JWT_SECRET: "{{ komodo_jwt_secret }}"
                KOMODO_JWT_TTL: "1-day"
                KOMODO_LOCAL_AUTH: "true"
                KOMODO_INIT_ADMIN_USERNAME: "{{ komodo_admin_username }}"
                KOMODO_INIT_ADMIN_PASSWORD: "{{ komodo_admin_password }}"
                KOMODO_DISABLE_USER_REGISTRATION: "false"
                KOMODO_ENABLE_NEW_USERS: "true"
                KOMODO_DISABLE_NON_ADMIN_CREATE: "false"
                KOMODO_TRANSPARENT_MODE: "false"
                KOMODO_LOGGING_PRETTY: "false"
                KOMODO_PRETTY_STARTUP_CONFIG: "false"
                KOMODO_PASSKEY: "{{ komodo_passkey }}"
                TZ: "{{ ansible_facts.date_time.tz }}"
              volumes:
                - "{{ komodo_backups_path }}:/backups"
                - "/var/run/docker.sock:/var/run/docker.sock"
              deploy:
                placement:
                  constraints:
                    - node.role == manager
                    - node.labels.role == cloud
                restart_policy:
                  condition: any
                  delay: 10s

            periphery:
              image: "ghcr.io/moghtech/komodo-periphery:{{ komodo_image_tag }}"
              user: root
              networks:
                - komodo_net
              ports:
                - target: 8120
                  published: 8120
                  mode: host
              environment:
                PERIPHERY_ROOT_DIRECTORY: "{{ periphery_root }}"
                PERIPHERY_PASSKEYS: "{{ komodo_passkey }}"
                PERIPHERY_DISABLE_TERMINALS: "false"
                PERIPHERY_SSL_ENABLED: "true"
                PERIPHERY_INCLUDE_DISK_MOUNTS: "/etc/hostname"
                PERIPHERY_LOGGING_PRETTY: "false"
                PERIPHERY_PRETTY_STARTUP_CONFIG: "false"
                TZ: "{{ ansible_facts.date_time.tz }}"
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - /proc:/proc
                - "{{ periphery_root }}:{{ periphery_root }}"
              deploy:
                mode: global
                restart_policy:
                  condition: any
                  delay: 10s

          networks:
            komodo_net:
              external: true
      when: is_cloud_leader

    - name: "Deploy Komodo stack"
      ansible.builtin.shell: |
        cd /opt/stacks/komodo && docker stack deploy -c docker-compose.yml komodo
      when: is_cloud_leader
      register: komodo_deploy_result
      changed_when: "'Creating' in komodo_deploy_result.stdout or 'Updating' in komodo_deploy_result.stdout"

    - name: "Wait for services to stabilize"
      ansible.builtin.pause:
        seconds: 10
      when: is_cloud_leader and not ansible_check_mode

    - name: "Check service status"
      ansible.builtin.shell: |
        docker service ls | grep komodo
      register: komodo_services
      changed_when: false
      when: is_cloud_leader and not ansible_check_mode

    - name: "Get cloud node Tailscale IP"
      ansible.builtin.set_fact:
        komodo_access_ip: "{{ ansible_facts['tailscale0'].ipv4.address }}"
      when: is_cloud_leader and 'tailscale0' in ansible_facts

    - name: "Display Komodo access information"
      ansible.builtin.debug:
        msg: |

          ============================================================
          KOMODO DEPLOYMENT COMPLETE
          ============================================================

          Komodo has been deployed with the following services:
          {{ komodo_services.stdout }}

          Access Komodo Core at:
            http://{{ komodo_access_ip | default(ansible_facts.default_ipv4.address) }}:9120

          Default credentials:
            Username: {{ komodo_admin_username }}
            Password: {{ komodo_admin_password }}

          IMPORTANT: Change the default password immediately!

          If services show 0/1, check logs with:
            docker service logs komodo_mongo
            docker service logs komodo_core
            docker service logs komodo_periphery

          ============================================================
      when: is_cloud_leader
      run_once: true

    - name: "Wait 30 seconds before checking logs"
      ansible.builtin.pause:
        seconds: 30
      when: is_cloud_leader and not ansible_check_mode

    - name: "Check Komodo service logs"
      ansible.builtin.shell: |
        echo "=== Komodo Core Logs ==="
        docker service logs komodo_core --tail 20
        echo ""
        echo "=== Komodo Mongo Logs ==="
        docker service logs komodo_mongo --tail 20
        echo ""
        echo "=== Komodo Periphery Logs ==="
        docker service logs komodo_periphery --tail 20
      register: komodo_logs
      changed_when: false
      when: is_cloud_leader and not ansible_check_mode

    - name: "Display Komodo service logs"
      ansible.builtin.debug:
        var: komodo_logs.stdout_lines
      when: is_cloud_leader and not ansible_check_mode
      run_once: true
