version: "3.9"

services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager # Optional: Managers usually have stable outgoing connections
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          memory: 64M

networks:
  proxy:
    external: true
